const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const code=fs.readFileSync(path.join(__dirname,'index.html'),'utf8').match(/<script>([\s\S]*)<\/script>/)[1];
class Element{constructor(){this.clientWidth=280;this.clientHeight=280;this.style={};this.children=[];this.classList={toggle(){},add(){},remove(){}};}appendChild(c){if(c.parentElement)c.parentElement.children=c.parentElement.children.filter(x=>x!==c);this.children.push(c);c.parentElement=this;}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this);this.parentElement=null;}setAttribute(){}querySelectorAll(){return []}addEventListener(){}getBoundingClientRect(){return {width:280,height:280}}getContext(){return new Proxy({},{get:()=>()=>{}})}}
function boot(store,fail=false){const els={},el=id=>els[id]??=new Element();el('cubeStage').appendChild(el('originalCube'));let clock=0;const ctx={document:{getElementById:el,createElement:()=>new Element(),querySelectorAll:()=>[]},devicePixelRatio:1,ResizeObserver:class{observe(){}},performance:{now:()=>clock},requestAnimationFrame:f=>{clock+=2000;f(clock)},setTimeout:f=>f(),console,localStorage:{getItem(k){if(fail)throw Error('blocked');return store[k]??null},setItem(k,v){if(fail)throw Error('quota');store[k]=v}}};vm.createContext(ctx);vm.runInContext(code,ctx);return{el,run:s=>vm.runInContext(s,ctx)};}
const snapshot=`JSON.stringify({selected,step,mode,playbackMs,showTracking,state:state.map(f=>[f.p,f.n,f.color]),cubies:originalCube.cubies.map(c=>[c.pos,c.orient])})`;
(async()=>{
for(let i=0;i<28;i++){
 const store={},a=boot(store);a.run(`setMode('practice');chooseCase(${i})`);const len=a.run('sequence.length');for(let j=0;j<Math.min(len,3);j++)await a.el('next').onclick();a.el('speed').value='1600';a.el('speed').onchange();a.el('tracking').onclick();const wanted=a.run(snapshot),persisted=JSON.stringify(store);const b=boot(store);assert.equal(JSON.stringify(store),persisted,'startup must not overwrite saved step');assert(b.run('pendingResume!==null'));b.el('resumePractice').onclick();assert.equal(b.run(snapshot),wanted,'preset restore '+i);assert.equal(b.run('playing'),false);
}
const store={},a=boot(store);a.run("setMode('practice');$('whiteExample').onclick();loadWhitePlan()");await a.el('next').onclick();await a.el('next').onclick();a.run('enteredWhites.clear()');a.el('speed').value='450';a.el('speed').onchange();const wanted=a.run(snapshot),b=boot(store);b.el('resumePractice').onclick();assert.equal(b.run(snapshot),wanted,'custom restore uses planned input, not edited draft');await b.el('prev').onclick();assert.equal(b.run('step'),1);b.el('reset').onclick();assert.equal(b.run('step'),0);
for(const value of ['bad JSON',JSON.stringify({version:1,mode:'practice',selected:99,step:0,speed:900,tracking:true}),JSON.stringify({version:1,mode:'practice',selected:28,step:100,speed:900,tracking:true,custom:[12,13,14,15]})]){const bad={'little-cube-practice-v1':value},c=boot(bad);assert.equal(c.run('pendingResume'),null);c.run("setMode('practice');chooseCase(1)");assert(c.run('checkedPracticeRecord(JSON.parse(localStorage.getItem(practiceStorageKey)))!==null'));}
const unavailable=boot({},true);unavailable.run("setMode('practice');chooseCase(1)");await unavailable.el('next').onclick();assert.equal(unavailable.run('step'),1);assert(unavailable.el('saveStatus').textContent.includes('unavailable'));
console.log('PASS: reload restores all 28 preset lessons and a generated custom plan, including sticker/cubie state, step, speed and tracking; startup preserves saved data and resume stays paused. Custom input remains correct after draft edits. Previous/restart work after resume. Corrupt/out-of-range records rejected, storage failure does not block practice. Mock DOM/storage only.');
})().catch(e=>{console.error(e);process.exitCode=1});
